/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multisender } from "./Multisender";
export * as factories from "./factories";
export { Multisender__factory } from "./factories/Multisender__factory";
